class Catch{

  final Type exception;

  const Catch(this.exception);

}